name: Run BDD Tests - GitHub Actions

# When to run this workflow
on:
  push:
    branches: [main, develop]  # Run when code is pushed to main or develop
  pull_request:
    branches: [main]           # Run when pull request is created on main
  schedule:
    - cron: '0 2 * * *'        # Run daily at 2 AM UTC

jobs:
  test:
    runs-on: windows-latest    # Use Windows runner (can also use ubuntu-latest, macos-latest)
    
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]  # Test on multiple Python versions
    
    steps:
    # Step 1: Get the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Install Playwright browsers
    - name: Install Playwright browsers
      run: |
        playwright install
    
    # Step 5: Run tests in QA environment (headless)
    - name: Run BDD Tests - QA Environment
      run: |
        pytest tests/test_runner.py --env=qa -v --html=reports/report.html --self-contained-html
    
    # Step 6: Upload HTML report as artifact
    - name: Upload Test Report
      if: always()  # Upload even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-report-python${{ matrix.python-version }}
        path: reports/report.html
    
    # Step 7: Upload screenshots of failed tests
    - name: Upload Screenshots
      if: failure()  # Upload only if tests failed
      uses: actions/upload-artifact@v3
      with:
        name: screenshots-python${{ matrix.python-version }}
        path: screenshots/
    
    # Step 8: Publish test results
    - name: Publish Test Results
      if: always()
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      with:
        files: reports/report.html
        check_name: Test Results - Python ${{ matrix.python-version }}

# ============================================
# ALTERNATIVE: Simple Test Execution
# ============================================
# Uncomment this section if you want a simpler workflow

# jobs:
#   simple-test:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v3
#     
#     - uses: actions/setup-python@v4
#       with:
#         python-version: '3.11'
#     
#     - run: |
#         pip install -r requirements.txt
#         playwright install
#         pytest tests/test_runner.py --env=qa -v
#     
#     - uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: test-results
#         path: reports/
